CREATE TABLE user
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  fullname VARCHAR(128),
  email VARCHAR(128) UNIQUE,
  password VARCHAR(128),
  validate_hash VARCHAR(128),
  is_validated INTEGER DEFAULT 0
);

CREATE TABLE gde
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128),
  path VARCHAR(128)
);

CREATE TABLE instance
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64) UNIQUE,
  description VARCHAR(256),
  type VARCHAR(64)
);

CREATE TABLE badge_details
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  instance_id INTEGER,
  image_name VARCHAR(256)
);

CREATE TABLE medal_details
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  instance_id INTEGER,
  image_name VARCHAR(256)
);

CREATE TABLE user_badge
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  user_id INTEGER,
  badge_id INTEGER
);

CREATE TABLE user_score
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  user_id INTEGER,
  instance_id INTEGER,
  score INTEGER
);

CREATE TABLE rule
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(64) UNIQUE,
  action VARCHAR(20),
  meaning VARCHAR(256),
  value VARCHAR(256),
  event VARCHAR(256),
  gde_id INTEGER,
  gde_type VARCHAR(20)
);

CREATE TABLE events
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(256) UNIQUE,
  type VARCHAR(64) DEFAULT "simple"
);

CREATE TABLE hooks
(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(256) UNIQUE,
  type VARCHAR(64) DEFAULT "simple"
);